name: Publish to Cloudflare Workers

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Deploy to Cloudflare Workers with Wrangler
        # You may pin to the exact commit or the version.
        # uses: cloudflare/wrangler-action@4c10c1822abba527d820b29e6333e7f5dac2cabd
        uses: cloudflare/wrangler-action@2.0.0
        with:
          # Your Cloudflare API Token
          apiToken: ${{ secrets.CF_API_TOKEN }}
          # A new line deliminated string of environment variable names that should be configured as Worker secrets
          secrets: |
              TOKEN
          # The Wrangler command you wish to run. For example: "publish" - this will publish your Worker
          command: publish ${{ secrets.WRANGLER_VARS }}
        env:
          TOKEN: ${{ secrets.TOKEN }}
